### ISSUE TITLE
Simple example from a Makefile.

### ISSUE THREAD

**Issue by lindenb** [common-workflow-language/workflows#1]
Hi

I'd like to know if I can easily convert a **Makefile** based workflow to **CWL**. For example, for the simple Makefile, want would be equivalent CWL file please ?

```make

database.dna :  seq1.rna seq2.rna seq3.rna
	cat seq1.rna seq2.rna seq3.rna | tr "U" "T" > database.dna && echo "Done"

seq3.rna : 
	echo "AUGAAGACUGACUCGAUCGAUCG" > seq3.rna

seq2.rna : 
	echo "AUGAAGACUGACUCGAUCGAUCG" > seq2.rna

seq1.rna : 
	echo "AUGAAGACUGACUCGAUCGAUCG" > seq1.rna
```

**Comment by tetron** [comment]
Hi @lindenb, sorry for the delay.

At 111 lines compared to 11 lines the CWL solution is more complex than the original makefile, but let me point out a few details.

* Each tool (echo, tr, cat) is wrapped as an individual reusable component
* The workflow is parameterized (unlike the supplied Makefile)
* The "get_sequences" and "translate_sequences" steps are scatter steps, so they can be processed in parallel

Also general advantages of CWL over plain Makefiles:
* You can specify Docker images to run certain components without going into the details of getting data into/out of the Docker container
* The wo
dna.cwl:
```yaml
#!/usr/bin/env cwl-runner

- id: "#rnaseq"
  class: CommandLineTool
  inputs:
    - id: "#sequence"
      type: string
      inputBinding: {}
  outputs:
    - id: "#seqout"
      type: File
      outputBinding:
        glob: rnaseq
  baseCommand: echo
  stdout: rnaseq

- id: "#cat"
  class: CommandLineTool
  inputs:
    - id: "#sequences"
      type:
        type: array
        items: File
      inputBinding: {}
    - id: "#catfilename"
      type: string
  outputs:
    - id: "#catout"
      type: File
      outputBinding:
        glob:
          engine: cwl:JsonPointer
          script: /job/catfilename
  baseCommand: cat
  stdout:
    engine: cwl:JsonPointer
    script: /job/catfilename


- id: "#tr"
  class: CommandLineTool
  inputs:
    - id: "#trinput"
      type: File
    - id: "#from"
      type: string
      inputBinding:
        position: 1
    - id: "#to"
      type: string
      inputBinding:
        position: 1
    - id: "#filename"
      type: string
  outputs:
    - id: "#trout"
      type: File
      outputBinding:
        glob:
          engine: cwl:JsonPointer
          script: /job/filename
  baseCommand: tr
  stdin:
    engine: cwl:JsonPointer
    script: /job/trinput/path
  stdout:
    engine: cwl:JsonPointer
    script: /job/filename


- id: "#main"
  class: Workflow
  inputs:
    - id: "#rna"
      type:
        type: array
        items: string
  outputs:
    - id: "#outfile"
      type: File
      source: "#combine_sequences.catout"

  requirements:
    - class: ScatterFeatureRequirement

  steps:
    - id: "#get_sequences"
      run: {import: "#rnaseq"}
      scatter: "#get_sequences.sequence"
      inputs:
        - { id: "#get_sequences.sequence", source: "#rna" }
      outputs:
        - { id: "#get_sequences.seqout" }

    - id: "#translate_sequences"
      run: {import: "#tr"}
      scatter: "#translate_sequences.trinput"
      inputs:
        - { id: "#translate_sequences.trinput", source: "#get_sequences.seqout" }
        - { id: "#translate_sequences.from", default: "U" }
        - { id: "#translate_sequences.to", default: "T" }
        - { id: "#combine_sequences.filename", default: "dna" }
      outputs:
        - { id: "#translate_sequences.trout" }

    - id: "#combine_sequences"
      run: {import: "#cat"}
      inputs:
        - { id: "#combine_sequences.sequences", source: "#translate_sequences.trout" }
        - { id: "#combine_sequences.catfilename", default: "database.dna" }
      outputs:
        - { id: "#combine_sequences.catout" }
```

dna-job.json
```
{
  "rna": ["AUGAAGACUGACUCGAUCGAUCG", "AUGAAGACUGACUCGAUCGAUCG", "AUGAAGACUGACUCGAUCGAUCG"]
}
